package com.amao.ad2.db;

import com.amao.ad2.model.AdExposure;
import com.amao.ad2.model.AdExposureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AdExposureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int countByExample(AdExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int deleteByExample(AdExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int insert(AdExposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int insertSelective(AdExposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    List<AdExposure> selectByExample(AdExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    AdExposure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") AdExposure record, @Param("example") AdExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int updateByExample(@Param("record") AdExposure record, @Param("example") AdExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int updateByPrimaryKeySelective(AdExposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ad_exposure
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    int updateByPrimaryKey(AdExposure record);
}