package com.amao.ad2.model;

import java.util.Date;

public class AdExposure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.id
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.ad_id
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Integer adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.launch_site
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private String launchSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.exposure_amount
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Integer exposureAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.web_icon
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private String webIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.order_index
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Integer orderIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.exposure_days
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Integer exposureDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.create_time
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.remark
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.is_validity
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private String isValidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ad_exposure.create_user
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    private Integer createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.id
     *
     * @return the value of t_ad_exposure.id
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.id
     *
     * @param id the value for t_ad_exposure.id
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.ad_id
     *
     * @return the value of t_ad_exposure.ad_id
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.ad_id
     *
     * @param adId the value for t_ad_exposure.ad_id
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.launch_site
     *
     * @return the value of t_ad_exposure.launch_site
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public String getLaunchSite() {
        return launchSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.launch_site
     *
     * @param launchSite the value for t_ad_exposure.launch_site
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setLaunchSite(String launchSite) {
        this.launchSite = launchSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.exposure_amount
     *
     * @return the value of t_ad_exposure.exposure_amount
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Integer getExposureAmount() {
        return exposureAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.exposure_amount
     *
     * @param exposureAmount the value for t_ad_exposure.exposure_amount
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setExposureAmount(Integer exposureAmount) {
        this.exposureAmount = exposureAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.web_icon
     *
     * @return the value of t_ad_exposure.web_icon
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public String getWebIcon() {
        return webIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.web_icon
     *
     * @param webIcon the value for t_ad_exposure.web_icon
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setWebIcon(String webIcon) {
        this.webIcon = webIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.order_index
     *
     * @return the value of t_ad_exposure.order_index
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Integer getOrderIndex() {
        return orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.order_index
     *
     * @param orderIndex the value for t_ad_exposure.order_index
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setOrderIndex(Integer orderIndex) {
        this.orderIndex = orderIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.exposure_days
     *
     * @return the value of t_ad_exposure.exposure_days
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Integer getExposureDays() {
        return exposureDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.exposure_days
     *
     * @param exposureDays the value for t_ad_exposure.exposure_days
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setExposureDays(Integer exposureDays) {
        this.exposureDays = exposureDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.create_time
     *
     * @return the value of t_ad_exposure.create_time
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.create_time
     *
     * @param createTime the value for t_ad_exposure.create_time
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.remark
     *
     * @return the value of t_ad_exposure.remark
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.remark
     *
     * @param remark the value for t_ad_exposure.remark
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.is_validity
     *
     * @return the value of t_ad_exposure.is_validity
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public String getIsValidity() {
        return isValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.is_validity
     *
     * @param isValidity the value for t_ad_exposure.is_validity
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setIsValidity(String isValidity) {
        this.isValidity = isValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ad_exposure.create_user
     *
     * @return the value of t_ad_exposure.create_user
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ad_exposure.create_user
     *
     * @param createUser the value for t_ad_exposure.create_user
     *
     * @mbggenerated Wed May 25 01:14:10 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }
}